apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-k8-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-k8-kube
  template:
    metadata:
      labels:
        app: poc-k8-kube
    spec:
      containers:
        - name: app
          image: 414795437038.dkr.ecr.us-east-1.amazonaws.com/demo:2.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
